import {
  ULID_PATTERN,
  ISO_TIMESTAMP_PATTERN,
  CRITERION_ID_PATTERN,
  CRITERION_KINDS,
  CRITERION_TEXT_MAX_CHARS,
  DECISION_REF_PATTERN,
} from './patterns.mjs';

export const THREAD_SCHEMA_VERSION = 2;

export const threadSchema = {
  $id: 'https://continuity-ledger/schema/thread.json',
  type: 'object',
  additionalProperties: false,
  required: [
    'schema_version',
    'id',
    'slug',
    'title',
    'status',
    'parent_id',
    'predecessor_id',
    'completion_criteria',
    'vcs_ref',
    'external_refs',
    'blocked_by',
    'abandoned_reason',
    'closure_statement',
    'spine',
    'created_at',
    'updated_at',
  ],
  properties: {
    schema_version: { type: 'integer', const: THREAD_SCHEMA_VERSION },
    id: { type: 'string', pattern: ULID_PATTERN },
    slug: { type: 'string', minLength: 1 },
    title: { type: 'string', minLength: 1 },
    status: { type: 'string', enum: ['active', 'paused', 'blocked', 'done', 'abandoned'] },
    parent_id: { type: ['string', 'null'], pattern: ULID_PATTERN },
    predecessor_id: { type: ['string', 'null'], pattern: ULID_PATTERN },
    completion_criteria: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'text', 'done', 'kind', 'struck_by'],
        properties: {
          id: { type: 'string', pattern: CRITERION_ID_PATTERN },
          text: { type: 'string', minLength: 1, maxLength: CRITERION_TEXT_MAX_CHARS },
          done: { type: 'boolean' },
          kind: { type: 'string', enum: [...CRITERION_KINDS] },
          struck_by: { type: ['string', 'null'], pattern: DECISION_REF_PATTERN },
        },
      },
    },
    vcs_ref: { type: ['string', 'null'] },
    external_refs: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['system', 'id', 'url'],
        properties: {
          system: { type: 'string' },
          id: { type: 'string' },
          url: { type: 'string' },
        },
      },
    },
    blocked_by: { type: ['string', 'null'] },
    abandoned_reason: { type: ['string', 'null'] },
    closure_statement: { type: ['string', 'null'] },
    spine: {
      type: 'object',
      additionalProperties: false,
      required: ['status', 'active_goal', 'next_step', 'open_risks', 'key_decisions', 'out_of_scope'],
      properties: {
        status: { type: 'string' },
        active_goal: { type: 'string' },
        next_step: { type: 'string' },
        open_risks: { type: 'array', items: { type: 'string' } },
        key_decisions: { type: 'array', items: { type: 'string' } },
        out_of_scope: { type: 'array', items: { type: 'string' } },
      },
    },
    created_at: { type: 'string', pattern: ISO_TIMESTAMP_PATTERN },
    updated_at: { type: 'string', pattern: ISO_TIMESTAMP_PATTERN },
  },
};
